// AUTO-GENERATED by `php artisan boardmate:export-enums`. Do not edit by hand.
// Source: boardmate/app/Enums

export const ApplicationStatus = {
  Pending: 'pending',
  Approved: 'approved',
  Declined: 'declined',
  Cancelled: 'cancelled',
  Expired: 'expired',
  MovedIn: 'moved_in',
} as const
export type ApplicationStatus = (typeof ApplicationStatus)[keyof typeof ApplicationStatus]
export const ApplicationStatusLabels: Record<ApplicationStatus, string> = {
  'pending': 'Waiting for the owner',
  'approved': 'Reserved',
  'declined': 'Declined',
  'cancelled': 'Cancelled',
  'expired': 'Expired',
  'moved_in': 'Moved in',
}

export const AuditEvent = {
  OwnerVerified: 'owner.verified',
  OwnerRejected: 'owner.rejected',
  OwnerSuspended: 'owner.suspended',
  OwnerReinstated: 'owner.reinstated',
  AccountSuspended: 'account.suspended',
  AccountUnsuspended: 'account.unsuspended',
  OwnerApplied: 'owner.applied',
  OwnerDetailsChanged: 'owner.details_changed',
  CaretakerInvited: 'caretaker.invited',
  CaretakerInvitationResent: 'caretaker.invitation_resent',
  CaretakerInvitationCancelled: 'caretaker.invitation_cancelled',
  CaretakerInvitationAccepted: 'caretaker.invitation_accepted',
  CaretakerInvitationDeclined: 'caretaker.invitation_declined',
  CaretakerAccessChanged: 'caretaker.access_changed',
  CaretakerRemoved: 'caretaker.removed',
  PropertyCreated: 'property.created',
  PropertyUpdated: 'property.updated',
  PropertyDeleted: 'property.deleted',
  PropertyPublished: 'property.published',
  PropertyUnpublished: 'property.unpublished',
  RoomAdded: 'room.added',
  RoomUpdated: 'room.updated',
  RoomRemoved: 'room.removed',
  RentalModeSwitched: 'property.rental_mode_switched',
  UnitsAdded: 'unit.added',
  UnitUpdated: 'unit.updated',
  UnitRemoved: 'unit.removed',
  UnitNotReadyChanged: 'unit.not_ready_changed',
  RentChanged: 'price.rent_changed',
  UtilityAmountChanged: 'price.utility_changed',
  UtilityAccountAdded: 'utility.added',
  UtilityAccountUpdated: 'utility.updated',
  UtilityAccountRemoved: 'utility.removed',
  SettingsChanged: 'property.settings_changed',
  PhotosChanged: 'property.photos_changed',
  CaretakerAssigned: 'caretaker.assigned',
  CaretakerUnassigned: 'caretaker.unassigned',
  BookingApproved: 'booking.approved',
  BookingDeclined: 'booking.declined',
  BookingCancelled: 'booking.cancelled',
  ReservationExpired: 'booking.expired',
  LeaderAppointed: 'room.leader_appointed',
  LeaderReplaced: 'room.leader_replaced',
  OccupantAdded: 'room.occupant_added',
  OccupantUpdated: 'room.occupant_updated',
  OccupantRemoved: 'room.occupant_removed',
  TenancyStarted: 'tenancy.started',
  ActivationOverridden: 'tenancy.activation_overridden',
  EmergencyContactChanged: 'tenancy.emergency_contact_changed',
  DiscountSet: 'tenancy.discount_set',
  DiscountEnded: 'tenancy.discount_ended',
  EmailChanged: 'account.email_changed',
  PasswordChanged: 'account.password_changed',
  PasswordSet: 'account.password_set',
  GoogleLinked: 'account.google_linked',
} as const
export type AuditEvent = (typeof AuditEvent)[keyof typeof AuditEvent]
export const AuditEventLabels: Record<AuditEvent, string> = {
  'owner.verified': 'Verified the owner account',
  'owner.rejected': 'Did not approve the owner application',
  'owner.suspended': 'Suspended the owner account',
  'owner.reinstated': 'Reinstated the owner account',
  'account.suspended': 'Suspended an account',
  'account.unsuspended': 'Lifted an account suspension',
  'owner.applied': 'Applied to be an owner',
  'owner.details_changed': 'Changed business or payment details',
  'caretaker.invited': 'Invited a caretaker',
  'caretaker.invitation_resent': 'Resent a caretaker invitation',
  'caretaker.invitation_cancelled': 'Cancelled a caretaker invitation',
  'caretaker.invitation_accepted': 'Accepted the caretaker invitation',
  'caretaker.invitation_declined': 'Declined the caretaker invitation',
  'caretaker.access_changed': 'Changed a caretaker\'s access',
  'caretaker.removed': 'Removed a caretaker',
  'property.created': 'Added a property',
  'property.updated': 'Changed property details',
  'property.deleted': 'Deleted a property',
  'property.published': 'Published a listing',
  'property.unpublished': 'Unpublished a listing',
  'room.added': 'Added a room',
  'room.updated': 'Changed a room',
  'room.removed': 'Removed a room',
  'property.rental_mode_switched': 'Switched a room\'s rental mode',
  'unit.added': 'Added units',
  'unit.updated': 'Changed a unit',
  'unit.removed': 'Removed a unit',
  'unit.not_ready_changed': 'Changed a unit\'s readiness',
  'price.rent_changed': 'Changed rent',
  'price.utility_changed': 'Changed a utility price',
  'utility.added': 'Added a utility',
  'utility.updated': 'Changed a utility',
  'utility.removed': 'Removed a utility',
  'property.settings_changed': 'Changed property settings',
  'property.photos_changed': 'Changed listing photos',
  'caretaker.assigned': 'Assigned a caretaker to a property',
  'caretaker.unassigned': 'Removed a caretaker from a property',
  'booking.approved': 'Approved a booking',
  'booking.declined': 'Declined a booking',
  'booking.cancelled': 'Cancelled a booking',
  'booking.expired': 'A reservation expired',
  'room.leader_appointed': 'Appointed a room leader',
  'room.leader_replaced': 'Replaced a room leader',
  'room.occupant_added': 'Added an occupant',
  'room.occupant_updated': 'Changed an occupant',
  'room.occupant_removed': 'Removed an occupant',
  'tenancy.started': 'Moved someone in',
  'tenancy.activation_overridden': 'Moved in without the deposit and first rent',
  'tenancy.emergency_contact_changed': 'Changed a tenant\'s emergency contact',
  'tenancy.discount_set': 'Set a tenant\'s discount',
  'tenancy.discount_ended': 'Ended a tenant\'s discount',
  'account.email_changed': 'Changed email',
  'account.password_changed': 'Changed password',
  'account.password_set': 'Set a password',
  'account.google_linked': 'Linked a Google account',
}

export const BilledBy = {
  Owner: 'owner',
  Group: 'group',
} as const
export type BilledBy = (typeof BilledBy)[keyof typeof BilledBy]
export const BilledByLabels: Record<BilledBy, string> = {
  'owner': 'Owner',
  'group': 'The boarders (shared among themselves)',
}

export const CaretakerAccessLevel = {
  Collector: 'collector',
  Manager: 'manager',
} as const
export type CaretakerAccessLevel = (typeof CaretakerAccessLevel)[keyof typeof CaretakerAccessLevel]
export const CaretakerAccessLevelLabels: Record<CaretakerAccessLevel, string> = {
  'collector': 'Collector',
  'manager': 'Manager',
}

export const CaretakerInvitationStatus = {
  Pending: 'pending',
  Accepted: 'accepted',
  Declined: 'declined',
  Revoked: 'revoked',
  Expired: 'expired',
} as const
export type CaretakerInvitationStatus = (typeof CaretakerInvitationStatus)[keyof typeof CaretakerInvitationStatus]
export const CaretakerInvitationStatusLabels: Record<CaretakerInvitationStatus, string> = {
  'pending': 'Waiting for reply',
  'accepted': 'Accepted',
  'declined': 'Declined',
  'revoked': 'Cancelled',
  'expired': 'Expired',
}

export const CorrectionCreditHandling = {
  RollForward: 'roll_forward',
  Refund: 'refund',
} as const
export type CorrectionCreditHandling = (typeof CorrectionCreditHandling)[keyof typeof CorrectionCreditHandling]
export const CorrectionCreditHandlingLabels: Record<CorrectionCreditHandling, string> = {
  'roll_forward': 'Roll forward to the next bill',
  'refund': 'Refund',
}

export const DepositRule = {
  OneMonthRent: 'one_month_rent',
  FixedAmount: 'fixed_amount',
  None: 'none',
} as const
export type DepositRule = (typeof DepositRule)[keyof typeof DepositRule]
export const DepositRuleLabels: Record<DepositRule, string> = {
  'one_month_rent': 'One month\'s rent',
  'fixed_amount': 'Fixed amount',
  'none': 'No deposit',
}

export const DiscountKind = {
  Fixed: 'fixed',
  Percent: 'percent',
} as const
export type DiscountKind = (typeof DiscountKind)[keyof typeof DiscountKind]
export const DiscountKindLabels: Record<DiscountKind, string> = {
  'fixed': 'Fixed amount',
  'percent': 'Percent',
}

export const DocumentType = {
  Receipt: 'receipt',
  Bill: 'bill',
  Notice: 'notice',
} as const
export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType]
export const DocumentTypeLabels: Record<DocumentType, string> = {
  'receipt': 'Official receipt',
  'bill': 'Bill',
  'notice': 'Formal notice',
}

export const DueDatePolicy = {
  Anniversary: 'anniversary',
  Common: 'common',
  Hybrid: 'hybrid',
} as const
export type DueDatePolicy = (typeof DueDatePolicy)[keyof typeof DueDatePolicy]
export const DueDatePolicyLabels: Record<DueDatePolicy, string> = {
  'anniversary': 'Each boarder\'s move-in date',
  'common': 'One date for everyone',
  'hybrid': 'Rent on move-in date, utilities on one date',
}

export const FilePurpose = {
  ProfilePhoto: 'profile_photo',
  ListingPhoto: 'listing_photo',
  IdDocument: 'id_document',
  OwnerDocument: 'owner_document',
} as const
export type FilePurpose = (typeof FilePurpose)[keyof typeof FilePurpose]
export const FilePurposeLabels: Record<FilePurpose, string> = {
  'profile_photo': 'Profile photo',
  'listing_photo': 'Listing photo',
  'id_document': 'ID',
  'owner_document': 'Owner document',
}

export const FinalUtilityHandling = {
  NoHoldback: 'no_holdback',
  HoldbackTrueUp: 'holdback_true_up',
  EstimateAndClose: 'estimate_and_close',
} as const
export type FinalUtilityHandling = (typeof FinalUtilityHandling)[keyof typeof FinalUtilityHandling]
export const FinalUtilityHandlingLabels: Record<FinalUtilityHandling, string> = {
  'no_holdback': 'No holdback',
  'holdback_true_up': 'Holdback + true-up',
  'estimate_and_close': 'Estimate and close',
}

export const LateFeeType = {
  Off: 'off',
  Fixed: 'fixed',
  Percentage: 'percentage',
} as const
export type LateFeeType = (typeof LateFeeType)[keyof typeof LateFeeType]
export const LateFeeTypeLabels: Record<LateFeeType, string> = {
  'off': 'Off',
  'fixed': 'Fixed amount',
  'percentage': 'Percentage of the charge',
}

export const NotificationEvent = {
  VerifyEmail: 'verify_email',
  PasswordReset: 'password_reset',
  Welcome: 'welcome',
  EmailChangeConfirm: 'email_change_confirm',
  EmailChangeNotice: 'email_change_notice',
  OwnerApplicationSubmitted: 'owner_application_submitted',
  OwnerApplicationApproved: 'owner_application_approved',
  OwnerApplicationRejected: 'owner_application_rejected',
  OwnerSuspended: 'owner_suspended',
  CaretakerInvitation: 'caretaker_invitation',
  CaretakerInvitationAccepted: 'caretaker_invitation_accepted',
  CaretakerAccessChanged: 'caretaker_access_changed',
  CaretakerRemoved: 'caretaker_removed',
  BookingReceived: 'booking_received',
  BookingApproved: 'booking_approved',
  BookingDeclined: 'booking_declined',
  BookingAutoCancelled: 'booking_auto_cancelled',
  BookingCancelled: 'booking_cancelled',
  ReservationExpiringSoon: 'reservation_expiring_soon',
  ReservationExpired: 'reservation_expired',
  TenancyStarted: 'tenancy_started',
  LeaderAppointed: 'leader_appointed',
  LeaderEnded: 'leader_ended',
  OccupantsChanged: 'occupants_changed',
  ApplicationWithdrawnOnMoveIn: 'application_withdrawn_on_move_in',
  DiscountChanged: 'discount_changed',
} as const
export type NotificationEvent = (typeof NotificationEvent)[keyof typeof NotificationEvent]
export const NotificationEventLabels: Record<NotificationEvent, string> = {
  'verify_email': 'Email verification',
  'password_reset': 'Password reset',
  'welcome': 'Welcome',
  'email_change_confirm': 'Confirm new email',
  'email_change_notice': 'Email change notice',
  'owner_application_submitted': 'New owner application',
  'owner_application_approved': 'Owner account approved',
  'owner_application_rejected': 'Owner application not approved',
  'owner_suspended': 'Owner account suspended',
  'caretaker_invitation': 'Caretaker invitation',
  'caretaker_invitation_accepted': 'Caretaker invitation accepted',
  'caretaker_access_changed': 'Caretaker access changed',
  'caretaker_removed': 'Removed as caretaker',
  'booking_received': 'New booking application',
  'booking_approved': 'Booking approved',
  'booking_declined': 'Booking declined',
  'booking_auto_cancelled': 'Booking withdrawn automatically',
  'booking_cancelled': 'Booking cancelled',
  'reservation_expiring_soon': 'Reservation expiring',
  'reservation_expired': 'Reservation expired',
  'tenancy_started': 'Moved in',
  'leader_appointed': 'Named room leader',
  'leader_ended': 'No longer room leader',
  'occupants_changed': 'Room occupants changed',
  'application_withdrawn_on_move_in': 'Application withdrawn after move-in',
  'discount_changed': 'Agreed rate changed',
}

export const OwnerDocumentKind = {
  GovernmentId: 'government_id',
  PropertyProof: 'property_proof',
  BusinessPermit: 'business_permit',
  Other: 'other',
} as const
export type OwnerDocumentKind = (typeof OwnerDocumentKind)[keyof typeof OwnerDocumentKind]
export const OwnerDocumentKindLabels: Record<OwnerDocumentKind, string> = {
  'government_id': 'Valid government ID',
  'property_proof': 'Proof of the property (title, lease, or a utility bill in your name)',
  'business_permit': 'Business or barangay permit',
  'other': 'Other document',
}

export const OwnerVerificationStatus = {
  Pending: 'pending',
  Verified: 'verified',
  Rejected: 'rejected',
  Suspended: 'suspended',
} as const
export type OwnerVerificationStatus = (typeof OwnerVerificationStatus)[keyof typeof OwnerVerificationStatus]
export const OwnerVerificationStatusLabels: Record<OwnerVerificationStatus, string> = {
  'pending': 'Under review',
  'verified': 'Verified',
  'rejected': 'Not approved',
  'suspended': 'Suspended',
}

export const PartialPeriodHandling = {
  Prorated: 'prorated',
  FullShifted: 'full_shifted',
  Waived: 'waived',
} as const
export type PartialPeriodHandling = (typeof PartialPeriodHandling)[keyof typeof PartialPeriodHandling]
export const PartialPeriodHandlingLabels: Record<PartialPeriodHandling, string> = {
  'prorated': 'Charge only the days stayed',
  'full_shifted': 'One full rent, longer first period',
  'waived': 'Free until the common due date',
}

export const PaymentMethod = {
  Cash: 'cash',
  BankTransfer: 'bank_transfer',
  EWallet: 'e_wallet',
} as const
export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod]
export const PaymentMethodLabels: Record<PaymentMethod, string> = {
  'cash': 'Cash',
  'bank_transfer': 'Bank transfer',
  'e_wallet': 'E-wallet (GCash, Maya)',
}

export const PropertyAbility = {
  View: 'view',
  RecordPayments: 'record_payments',
  ConfirmPaymentProofs: 'confirm_payment_proofs',
  SendReminders: 'send_reminders',
  MarkLate: 'mark_late',
  ApproveMoveOut: 'approve_move_out',
  ViewArrears: 'view_arrears',
  EditDetails: 'edit_details',
  ManagePrices: 'manage_prices',
  ManageRules: 'manage_rules',
  ManageUnits: 'manage_units',
  ManageUtilityBills: 'manage_utility_bills',
  EditIssuedBills: 'edit_issued_bills',
  ApproveBookings: 'approve_bookings',
  ManageTenancies: 'manage_tenancies',
  ManageSettlements: 'manage_settlements',
  RefundDeposits: 'refund_deposits',
  PublishListing: 'publish_listing',
  ViewCollections: 'view_collections',
  ManageCaretakers: 'manage_caretakers',
  EditOwnerPaymentDetails: 'edit_owner_payment_details',
  DeleteProperty: 'delete_property',
  TransferOwnership: 'transfer_ownership',
  ViewAuditLog: 'view_audit_log',
} as const
export type PropertyAbility = (typeof PropertyAbility)[keyof typeof PropertyAbility]

export const PropertyType = {
  Apartment: 'apartment',
  Dorm: 'dorm',
  BoardingHouse: 'boarding_house',
  MiniHouse: 'mini_house',
  Studio: 'studio',
} as const
export type PropertyType = (typeof PropertyType)[keyof typeof PropertyType]
export const PropertyTypeLabels: Record<PropertyType, string> = {
  'apartment': 'Apartment',
  'dorm': 'Dorm',
  'boarding_house': 'Boarding house',
  'mini_house': 'Mini house',
  'studio': 'Studio',
}

export const RentalMode = {
  Whole: 'whole',
  Bedspaces: 'bedspaces',
} as const
export type RentalMode = (typeof RentalMode)[keyof typeof RentalMode]
export const RentalModeLabels: Record<RentalMode, string> = {
  'whole': 'Whole room',
  'bedspaces': 'By bedspace',
}

export const ShortNoticeConsequence = {
  None: 'none',
  FixedFee: 'fixed_fee',
  DepositDeduction: 'deposit_deduction',
} as const
export type ShortNoticeConsequence = (typeof ShortNoticeConsequence)[keyof typeof ShortNoticeConsequence]
export const ShortNoticeConsequenceLabels: Record<ShortNoticeConsequence, string> = {
  'none': 'Nothing (flag only)',
  'fixed_fee': 'Fixed fee',
  'deposit_deduction': 'Deduct from deposit',
}

export const SplitManager = {
  Owner: 'owner',
  LeaseHolder: 'lease_holder',
} as const
export type SplitManager = (typeof SplitManager)[keyof typeof SplitManager]
export const SplitManagerLabels: Record<SplitManager, string> = {
  'owner': 'Owner',
  'lease_holder': 'Lease holder',
}

export const SplitMethod = {
  Equal: 'equal',
  Weights: 'weights',
  OccupantDays: 'occupant_days',
  Custom: 'custom',
  FixedPlusRemainder: 'fixed_plus_remainder',
  WeightedAbsorb: 'weighted_absorb',
} as const
export type SplitMethod = (typeof SplitMethod)[keyof typeof SplitMethod]
export const SplitMethodLabels: Record<SplitMethod, string> = {
  'equal': 'Equal',
  'weights': 'By weight',
  'occupant_days': 'By days stayed',
  'custom': 'Fixed amounts',
  'fixed_plus_remainder': 'Fixed + remainder',
  'weighted_absorb': 'By weight, landlord covers the rest',
}

export const TenancyPaymentKind = {
  Deposit: 'deposit',
  FirstRent: 'first_rent',
} as const
export type TenancyPaymentKind = (typeof TenancyPaymentKind)[keyof typeof TenancyPaymentKind]
export const TenancyPaymentKindLabels: Record<TenancyPaymentKind, string> = {
  'deposit': 'Deposit',
  'first_rent': 'First rent (advance)',
}

export const TenancyStatus = {
  Active: 'active',
} as const
export type TenancyStatus = (typeof TenancyStatus)[keyof typeof TenancyStatus]
export const TenancyStatusLabels: Record<TenancyStatus, string> = {
  'active': 'Active',
}

export const UnitKind = {
  Whole: 'whole',
  Bedspace: 'bedspace',
} as const
export type UnitKind = (typeof UnitKind)[keyof typeof UnitKind]
export const UnitKindLabels: Record<UnitKind, string> = {
  'whole': 'Whole room',
  'bedspace': 'Bedspace',
}

export const UnitStatus = {
  Available: 'available',
  Reserved: 'reserved',
  Occupied: 'occupied',
  Leaving: 'leaving',
  Overstaying: 'overstaying',
} as const
export type UnitStatus = (typeof UnitStatus)[keyof typeof UnitStatus]
export const UnitStatusLabels: Record<UnitStatus, string> = {
  'available': 'Available',
  'reserved': 'Reserved',
  'occupied': 'Occupied',
  'leaving': 'Leaving',
  'overstaying': 'Overstaying',
}

export const UserRole = {
  PlatformAdmin: 'platform_admin',
  Owner: 'owner',
  Caretaker: 'caretaker',
  Boarder: 'boarder',
} as const
export type UserRole = (typeof UserRole)[keyof typeof UserRole]
export const UserRoleLabels: Record<UserRole, string> = {
  'platform_admin': 'Platform admin',
  'owner': 'Owner',
  'caretaker': 'Caretaker',
  'boarder': 'Boarder',
}

export const UtilityDueRule = {
  DaysAfterIssue: 'days_after_issue',
  WithNextRent: 'with_next_rent',
} as const
export type UtilityDueRule = (typeof UtilityDueRule)[keyof typeof UtilityDueRule]
export const UtilityDueRuleLabels: Record<UtilityDueRule, string> = {
  'days_after_issue': 'A set number of days after the bill is entered',
  'with_next_rent': 'With the next rent',
}

export const UtilityMethod = {
  FixedPerBedspace: 'fixed_per_bedspace',
  FixedPerProperty: 'fixed_per_property',
  ActualBill: 'actual_bill',
  Included: 'included',
  OptIn: 'opt_in',
} as const
export type UtilityMethod = (typeof UtilityMethod)[keyof typeof UtilityMethod]
export const UtilityMethodLabels: Record<UtilityMethod, string> = {
  'fixed_per_bedspace': 'Fixed per bedspace',
  'fixed_per_property': 'Fixed per property',
  'actual_bill': 'Actual bill',
  'included': 'Included in rent',
  'opt_in': 'Opt-in',
}

export const UtilityType = {
  Electricity: 'electricity',
  Water: 'water',
  Internet: 'internet',
  Other: 'other',
} as const
export type UtilityType = (typeof UtilityType)[keyof typeof UtilityType]
export const UtilityTypeLabels: Record<UtilityType, string> = {
  'electricity': 'Electricity',
  'water': 'Water',
  'internet': 'Internet',
  'other': 'Other',
}
